---

- hosts: all
#  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == ["Zorin OS", "LMDE", "Ubuntu"]  

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
