---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu, LMDE and Zorin OS servers)
    tags: always,cache,distro_update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "LMDE", "Zorin OS"]

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Zorin servers
    tags: zorin,apache,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Zorin OS"

  - name: copy default html file for site
    tags: apache,php
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: file_servers
  become: true
  tasks:

  - name: Install file servers
    tags: mint,samba
    package:
      name: samba
      state: latest
    when: ansible_distribution == "LMDE"
