---

- hosts: web_servers
  become: true
  tasks:

  - name: Update repository index and install apache and php packages
    tags: apache,php,zorin
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["LMDE", "Zorin OS"]

  - name: copy default html file for site
    tags: apache,php,zorin
    copy:
      src: /home/neil/ansible/files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
