---

- hosts: all
#  become: true
  tasks:

  - name: Update repository index and uninstall apache and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution in ["LMDE", "Zorin OS"]
